### ISSUE TITLE
Better healthcheck ?

### ISSUE THREAD

**Issue by Fredouye** [heyValdemar/keycloak-traefik-letsencrypt-docker-compose#6]
Hi

Keycloak can expose the `/health` [endpoint](https://www.keycloak.org/server/management-interface), which seems to be a more accurate way to check the application.

Here's what I'm using :

```yaml
  keycloak:
    image: keycloak/keycloak:25.0.4-0
    environment:
      KC_HEALTH_ENABLED: true
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "exec 3<>/dev/tcp/localhost/9000 && echo -e 'GET /health/ready HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n' >&3 && cat <&3 | grep -q '200 OK'"
        ]
      interval: 30s
      timeout: 5s
      retries: 20
```

**Comment by heyvaldemar** [comment]
hey @Fredouye,

Thanks for sending over your setup for the Keycloak health checks! It’s great to see you using the `/health/ready` endpoint to ensure everything is running smoothly. Your method of checking both the TCP connection and the HTTP response is thorough and really ensures that Keycloak is not just up but also ready to handle requests.

If you’re looking for ways to make the health check command a bit easier to follow, you might want to consider splitting it across several lines. This can make it a lot easier to read and maintain, especially if you need to make adjustments down the line. Here’s a quick example of how you could structure it:

```yaml
    healthcheck:
      test: 
      - "CMD-SHELL"
      - |
        exec 3<>/dev/tcp/localhost/9000 &&
        echo -e 'GET /health/ready HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n' >&3 &&
        cat <&3 | tee /tmp/healthcheck.log | grep -q '200 OK'
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
```

I added a bit where it logs the response to a file, which can be really handy for debugging if anything goes sideways.

Also, if you’re interested in discussing more about DevOps or have more questions, feel free to join my DevOps community on Discord [here](https://discord.gg/AJQGCCBcqf). It’s a great place to share, learn, and collaborate with others in the field.

Let me know what you think or if there's anything else you need a hand with!

Cheers!
